// client/src/utils/teamColors.js - Complete team colors for all sports
export const getTeamColor = (teamName, sport = 'MLB') => {
  const teamColors = {
    // MLB Teams
    'Arizona Diamondbacks': 'bg-red-700',
    'Atlanta Braves': 'bg-red-600',
    'Baltimore Orioles': 'bg-orange-600',
    'Boston Red Sox': 'bg-red-600',
    'Chicago Cubs': 'bg-blue-500',
    'Chicago White Sox': 'bg-gray-800',
    'Cincinnati Reds': 'bg-red-600',
    'Cleveland Guardians': 'bg-red-700',
    'Colorado Rockies': 'bg-purple-600',
    'Detroit Tigers': 'bg-orange-600',
    'Houston Astros': 'bg-orange-600',
    'Kansas City Royals': 'bg-blue-600',
    'Los Angeles Angels': 'bg-red-600',
    'Los Angeles Dodgers': 'bg-blue-800',
    'Miami Marlins': 'bg-blue-400',
    'Milwaukee Brewers': 'bg-blue-700',
    'Minnesota Twins': 'bg-red-600',
    'New York Mets': 'bg-blue-600',
    'New York Yankees': 'bg-gray-700',
    'Oakland Athletics': 'bg-green-600',
    'Philadelphia Phillies': 'bg-red-500',
    'Pittsburgh Pirates': 'bg-yellow-500',
    'San Diego Padres': 'bg-yellow-600',
    'San Francisco Giants': 'bg-orange-500',
    'Seattle Mariners': 'bg-teal-600',
    'St. Louis Cardinals': 'bg-red-600',
    'Tampa Bay Rays': 'bg-blue-600',
    'Texas Rangers': 'bg-blue-700',
    'Toronto Blue Jays': 'bg-blue-600',
    'Washington Nationals': 'bg-red-500',

    // NFL Teams
    'Arizona Cardinals': 'bg-red-700',
    'Atlanta Falcons': 'bg-red-600',
    'Baltimore Ravens': 'bg-purple-800',
    'Buffalo Bills': 'bg-blue-600',
    'Carolina Panthers': 'bg-blue-500',
    'Chicago Bears': 'bg-orange-600',
    'Cincinnati Bengals': 'bg-orange-500',
    'Cleveland Browns': 'bg-orange-700',
    'Dallas Cowboys': 'bg-blue-800',
    'Denver Broncos': 'bg-orange-600',
    'Detroit Lions': 'bg-blue-600',
    'Green Bay Packers': 'bg-green-600',
    'Houston Texans': 'bg-red-700',
    'Indianapolis Colts': 'bg-blue-600',
    'Jacksonville Jaguars': 'bg-teal-600',
    'Kansas City Chiefs': 'bg-red-600',
    'Las Vegas Raiders': 'bg-gray-800',
    'Los Angeles Chargers': 'bg-blue-500',
    'Los Angeles Rams': 'bg-blue-800',
    'Miami Dolphins': 'bg-teal-500',
    'Minnesota Vikings': 'bg-purple-600',
    'New England Patriots': 'bg-blue-800',
    'New Orleans Saints': 'bg-yellow-600',
    'New York Giants': 'bg-blue-600',
    'New York Jets': 'bg-green-600',
    'Philadelphia Eagles': 'bg-green-700',
    'Pittsburgh Steelers': 'bg-yellow-500',
    'San Francisco 49ers': 'bg-red-600',
    'Seattle Seahawks': 'bg-blue-700',
    'Tampa Bay Buccaneers': 'bg-red-700',
    'Tennessee Titans': 'bg-blue-600',
    'Washington Commanders': 'bg-red-700',

    // NBA Teams
    'Atlanta Hawks': 'bg-red-600',
    'Boston Celtics': 'bg-green-600',
    'Brooklyn Nets': 'bg-gray-800',
    'Charlotte Hornets': 'bg-teal-500',
    'Chicago Bulls': 'bg-red-600',
    'Cleveland Cavaliers': 'bg-red-700',
    'Dallas Mavericks': 'bg-blue-600',
    'Denver Nuggets': 'bg-blue-500',
    'Detroit Pistons': 'bg-red-600',
    'Golden State Warriors': 'bg-blue-600',
    'Houston Rockets': 'bg-red-600',
    'Indiana Pacers': 'bg-blue-600',
    'Los Angeles Clippers': 'bg-blue-700',
    'Los Angeles Lakers': 'bg-purple-600',
    'Memphis Grizzlies': 'bg-blue-700',
    'Miami Heat': 'bg-red-600',
    'Milwaukee Bucks': 'bg-green-600',
    'Minnesota Timberwolves': 'bg-blue-600',
    'New Orleans Pelicans': 'bg-blue-700',
    'New York Knicks': 'bg-blue-600',
    'Oklahoma City Thunder': 'bg-blue-600',
    'Orlando Magic': 'bg-blue-600',
    'Philadelphia 76ers': 'bg-blue-600',
    'Phoenix Suns': 'bg-orange-600',
    'Portland Trail Blazers': 'bg-red-600',
    'Sacramento Kings': 'bg-purple-600',
    'San Antonio Spurs': 'bg-gray-700',
    'Toronto Raptors': 'bg-red-600',
    'Utah Jazz': 'bg-blue-700',
    'Washington Wizards': 'bg-red-600',

    // College Football (Major Programs)
    'Alabama': 'bg-red-700',
    'Auburn': 'bg-orange-600',
    'Arkansas': 'bg-red-600',
    'Florida': 'bg-blue-600',
    'Georgia': 'bg-red-700',
    'Kentucky': 'bg-blue-600',
    'LSU': 'bg-purple-600',
    'Mississippi State': 'bg-red-700',
    'Missouri': 'bg-yellow-600',
    'Ole Miss': 'bg-blue-600',
    'South Carolina': 'bg-red-700',
    'Tennessee': 'bg-orange-600',
    'Texas A&M': 'bg-red-700',
    'Vanderbilt': 'bg-yellow-600',
    'Clemson': 'bg-orange-600',
    'Duke': 'bg-blue-600',
    'Florida State': 'bg-red-700',
    'Georgia Tech': 'bg-yellow-600',
    'Louisville': 'bg-red-600',
    'Miami': 'bg-orange-600',
    'North Carolina': 'bg-blue-600',
    'NC State': 'bg-red-600',
    'Pittsburgh': 'bg-blue-600',
    'Syracuse': 'bg-orange-600',
    'Virginia': 'bg-blue-600',
    'Virginia Tech': 'bg-red-700',
    'Wake Forest': 'bg-yellow-600',
    'Illinois': 'bg-orange-600',
    'Indiana': 'bg-red-600',
    'Iowa': 'bg-yellow-600',
    'Maryland': 'bg-red-600',
    'Michigan': 'bg-blue-600',
    'Michigan State': 'bg-green-600',
    'Minnesota': 'bg-red-700',
    'Nebraska': 'bg-red-600',
    'Northwestern': 'bg-purple-600',
    'Ohio State': 'bg-red-700',
    'Penn State': 'bg-blue-600',
    'Purdue': 'bg-yellow-600',
    'Rutgers': 'bg-red-600',
    'Wisconsin': 'bg-red-600',
    'Baylor': 'bg-green-600',
    'Iowa State': 'bg-red-600',
    'Kansas': 'bg-blue-600',
    'Kansas State': 'bg-purple-600',
    'Oklahoma': 'bg-red-700',
    'Oklahoma State': 'bg-orange-600',
    'TCU': 'bg-purple-600',
    'Texas': 'bg-orange-600',
    'Texas Tech': 'bg-red-600',
    'West Virginia': 'bg-blue-600',
    'Arizona': 'bg-red-600',
    'Arizona State': 'bg-red-700',
    'California': 'bg-blue-600',
    'Colorado': 'bg-yellow-600',
    'Oregon': 'bg-green-600',
    'Oregon State': 'bg-orange-600',
    'Stanford': 'bg-red-600',
    'UCLA': 'bg-blue-600',
    'USC': 'bg-red-700',
    'Utah': 'bg-red-600',
    'Washington': 'bg-purple-600',
    'Washington State': 'bg-red-700',
    'Notre Dame': 'bg-blue-600'
  };

  return teamColors[teamName] || 'bg-gray-500';
};

// Sport-specific color fallbacks
export const getSportColors = (sport) => {
  const sportColors = {
    'MLB': { primary: 'bg-blue-600', secondary: 'bg-red-600' },
    'NFL': { primary: 'bg-green-600', secondary: 'bg-orange-600' },
    'NBA': { primary: 'bg-purple-600', secondary: 'bg-yellow-600' },
    'CFB': { primary: 'bg-red-600', secondary: 'bg-blue-600' }
  };
  
  return sportColors[sport] || sportColors['MLB'];
};

// Updated ActionStyleGameCard team color functions
export const getHomeColor = (homeTeam, sport = 'MLB') => {
  return getTeamColor(homeTeam, sport);
};

export const getAwayColor = (awayTeam, sport = 'MLB') => {
  return getTeamColor(awayTeam, sport);
};
